name: yaf
license: GPL2
autotools:
  configure:
    args:
      - --enable-applabel
      - --enable-mpls
      - --enable-plugins
dependencies:
  - glib2 >= 2.6.4
  - libfixbuf
  - libpcap
  - pcre
build_dependencies:
  - pkg-config
